/*
    Copyright © 2025 Gaël Fortier <gael.fortier.1@ens.etsmtl.ca>
*/

#include "cdocs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

static void _cdocs_generate_function_doc(FILE* file, _cdocs_fn_struct* function) {
    fprintf(file, "---\n");
    fprintf(file, "%s `%s`\n", "##", function->function.name);
    fprintf(file, "%s Description\n%s\n", "###", function->function.description);
    fprintf(file, "%s Returns: `%s`\n%s\n", "###", function->returns.returns, function->returns.description);
    fprintf(file, "%s Parameters\n", "###");

    _cdocs_fn_p_struct* it = function->parameters;
    while(it->signature != NULL) {
        fprintf(file, "`%s` : %s\n", it->signature, it->description);
        it++;
    }
    fprintf(file, "\n");
}

void _cdocs_generate_documentation_x(const char* filename, const char* subject, size_t size, _cdocs_fn_struct* functions) {
    assert(filename != NULL);
    assert(subject != NULL);
    assert(functions != NULL);

    FILE* document = fopen(filename, "w+");
    assert(document != NULL);
    fprintf(document, "<!-- Generated by cdocs. -->\n");
    fprintf(document, "%s %s\n\n", "#", subject);
    for(size_t i = 0; i < size; i++) {
        _cdocs_generate_function_doc(document, &functions[i]);
    }
    fclose(document);
}
